//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCopy.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HCopy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pause に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonPause_Pause {
            get {
                return ResourceManager.GetString("ButtonPause_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resume に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonPause_Resume {
            get {
                return ResourceManager.GetString("ButtonPause_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Abort quit({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonQuit_AutoQuitFmt {
            get {
                return ResourceManager.GetString("ButtonQuit_AutoQuitFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonQuit_Quit {
            get {
                return ResourceManager.GetString("ButtonQuit_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compressed settings are ignored in HTTP connection mode. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CompressModeIgnored {
            get {
                return ResourceManager.GetString("CompressModeIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (none) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EmptyText {
            get {
                return ResourceManager.GetString("EmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{1}&quot; not found in &quot;{0}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorChecksumNotFound {
            get {
                return ResourceManager.GetString("ErrorChecksumNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid parameter: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidOptionFmt {
            get {
                return ResourceManager.GetString("InvalidOptionFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogFormatAborted {
            get {
                return ResourceManager.GetString("LogFormatAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compressing {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogFormatCompressing {
            get {
                return ResourceManager.GetString("LogFormatCompressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copying {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogFormatCopy {
            get {
                return ResourceManager.GetString("LogFormatCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copying {0} (compressed) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogFormatCopyCompressed {
            get {
                return ResourceManager.GetString("LogFormatCopyCompressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogFormatException {
            get {
                return ResourceManager.GetString("LogFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}: Failed to copy by compressed, start copying normally に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogFormatFailToExtract {
            get {
                return ResourceManager.GetString("LogFormatFailToExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ***Finished*** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogFormatFinished {
            get {
                return ResourceManager.GetString("LogFormatFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}: Fail to read at line {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogFormatInvalidChecksumEntry {
            get {
                return ResourceManager.GetString("LogFormatInvalidChecksumEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogFormatNoMessage {
            get {
                return ResourceManager.GetString("LogFormatNoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pause に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogFormatPaused {
            get {
                return ResourceManager.GetString("LogFormatPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resume に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogFormatResumed {
            get {
                return ResourceManager.GetString("LogFormatResumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update prohibited に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogFormatSuppressUpdating {
            get {
                return ResourceManager.GetString("LogFormatSuppressUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Waiting for {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogFormatWaitLocked {
            get {
                return ResourceManager.GetString("LogFormatWaitLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy processing is in progress. Do you want to abort? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_AbortCopy {
            get {
                return ResourceManager.GetString("MessageBox_AbortCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_Confirm {
            get {
                return ResourceManager.GetString("MessageBox_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_Error {
            get {
                return ResourceManager.GetString("MessageBox_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HCopyW に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_Usage {
            get {
                return ResourceManager.GetString("MessageBox_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no parameter following {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ParameterRequiedFmt {
            get {
                return ResourceManager.GetString("ParameterRequiedFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HCopyW &lt;source-dir&gt; &lt;destination-dir&gt; [options]
        ///HCopyW copies files from &lt;source-dir&gt; listed in &quot;_checksum.sha&quot;.
        ///
        ///Options:
        ///  --wait &lt;file&gt;
        ///  -w &lt;file&gt;
        ///      Wait for the &lt;file&gt; write lock to be released before starting copying.
        ///
        ///  --run &lt;executable&gt;
        ///  -r &lt;executable&gt;
        ///      Starts the program specified by &lt;executable&gt; after copying is completed.
        ///
        ///  --param &lt;parameters&gt;
        ///  -p &lt;parameters&gt;
        ///      Specify the parameters for executing the program specified by --run.
        ///      If there are multiple param [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
    }
}
