//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildSum.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuildSum.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0}: No such directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirectoryNotFoundFmt {
            get {
                return ResourceManager.GetString("DirectoryNotFoundFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot specify multiple --ignore-list に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_MultipleOption {
            get {
                return ResourceManager.GetString("Error_MultipleOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --ignore and --ignore-list cannot be specified at the same time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_OptionConfliected {
            get {
                return ResourceManager.GetString("Error_OptionConfliected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogFormatAborted {
            get {
                return ResourceManager.GetString("LogFormatAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compressing {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogFormatCompressing {
            get {
                return ResourceManager.GetString("LogFormatCompressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogFormatException {
            get {
                return ResourceManager.GetString("LogFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ***Finished*** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogFormatFinished {
            get {
                return ResourceManager.GetString("LogFormatFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogFormatNoMessage {
            get {
                return ResourceManager.GetString("LogFormatNoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pause に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogFormatPaused {
            get {
                return ResourceManager.GetString("LogFormatPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resume に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogFormatResumed {
            get {
                return ResourceManager.GetString("LogFormatResumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update prohibited に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogFormatSuppressUpdating {
            get {
                return ResourceManager.GetString("LogFormatSuppressUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updating _checksum.sha. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogFormatUpdatingChecksum {
            get {
                return ResourceManager.GetString("LogFormatUpdatingChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no parameter following {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ParameterRequiedFmt {
            get {
                return ResourceManager.GetString("ParameterRequiedFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BuildSum [&lt;target-dir&gt;] [options]
        ///BuildSum generates a SHA1 checksum named &quot;_checksum.sha&quot; from files in &lt;target-dir&gt;.
        ///If &lt;target-dir&gt; is omitted, use current directory.
        ///
        ///Options:
        ///  --compress &lt;compress-dir&gt;
        ///  -c &lt;compress-dir&gt;
        ///      Directory for storing compressed files.
        ///      You can reduce the load on the network by using compressed files.
        ///      If specified as a relative path, it will be a relative path from &lt;target-dir&gt;.
        ///
        ///  --ignore &lt;name&gt;
        ///  -i &lt;name&gt;
        ///      file or directory name to ignor [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
    }
}
