$namespace="HCopy"

$srcfile = "MainForm.Precopy.cs"
$class = "MainForm"
$varname = "PreCopyFiles"
$bindir = "bin\Debug\net9.0-windows10.0.22000.0"


pushd $bindir

$files = ""
Get-ChildItem -Recurse -File | foreach {
  $f =  Resolve-Path  -Relative $_.FullName
  $f = $f -replace '^\.\\', ''
  $f = $f -replace '\\', '" + Path.DirectorySeparatorChar + "'
  $files += "`r`n            """ + $f + ""","
}
popd

$src = @"
// This file is generated by "UpdatePreCopy.ps1".
// $varname is listed all files in $bindir
using System.IO;

namespace $namespace
{
    partial class $class
    {
        public static readonly string[] $varname = new string[]
        {$files
        };
    }
}
"@
echo $src | Out-File -FilePath $srcfile
