$namespace="HCopy"

$exename = "HCopyW.exe"
$srcfile = "MainForm.Precopy.cs"
$class = "MainForm"
$varname = "PreCopyFiles"
$bindir = "bin\Debug\net9.0-windows10.0.22000.0"


pushd $bindir
$indent = "            "
$files = $indent + """" + $exename + """"
Get-ChildItem -Recurse -File | foreach {
  $f =  Resolve-Path  -Relative $_.FullName
  $f = $f -replace '^\.\\', ''
  $f = $f -replace '\\', '" + Path.DirectorySeparatorChar + "'
  if ($f -ne $exename) {
	$files += ",`r`n" + $indent + """" + $f + """"
  }
}
popd

$src = @"
// This file is generated by "UpdatePreCopy.ps1".
// $varname is listed all files in $bindir
using System.IO;

namespace $namespace
{
	partial class $class
	{
		public static readonly string[] $varname = new string[]
		{
			// first item must be ".exe"
$files
		};
	}
}
"@
echo $src | Out-File -FilePath $srcfile
