//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCopy.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HCopy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   不明なオプション: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidOptionFmt {
            get {
                return ResourceManager.GetString("InvalidOptionFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}に続くパラメータがありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ParameterRequiedFmt {
            get {
                return ResourceManager.GetString("ParameterRequiedFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   hcopy &lt;source-dir&gt; &lt;destination-dir&gt; [options]
        ///hcopyはsource-dirから checksum.md5 に列挙されたファイルをコピーする。
        ///
        ///Options:
        ///  --wait &lt;file&gt;
        ///  -w &lt;file&gt;
        ///      指定したファイルの書き込みロックが解除されるまで待ってからコピーを開始する。
        ///
        ///  --run &lt;executable&gt;
        ///  -r &lt;executable&gt;
        ///      コピーの終了後に指定したプログラムを起動する。
        ///
        ///  --param &lt;parameters&gt;
        ///  -p &lt;parameters&gt;
        ///      --run で指定したプログラムを実行する際のパラメータを指定する。
        ///      複数ある場合は&quot;で括る。
        ///
        ///  --compress &lt;directory&gt;
        ///  -c &lt;directory&gt;
        ///      コピー高速化のため圧縮されたファイルを格納しているディレクトリを指定する
        ///      &lt;source-dir&gt;からの相対パス指定可
        ///
        ///  --help
        ///      このヘルプを [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
    }
}
